version: '3'

services:
  frontend:
    image: react-frontend
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    environment:
      - RVITE_API_URL=http://fastapi-backend:8000/api # Environment variable for API URL
    networks:
      - app-network

  backend:
    image: fastapi-backend
    container_name: fastapi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:80"
    networks:
      - app-network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  app-network:

volumes:
  postgres-data:
  data:
  letsencrypt: